# Generated by Django 5.2.3 on 2025-07-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_chat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
